#fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          [types-setuptools, types-requests, types-PyYAML]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject] # Flake8 plug-in loading the configuration from pyproject.toml